apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: v-black-friday-v2-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9, pipelines.kubeflow.org/pipeline_compilation_time: '2021-12-07T11:54:48.382686',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "v=black-friday-v2"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.9}
spec:
  entrypoint: v-black-friday-v2
  templates:
  - name: clean-data
    container:
      args: []
      command: [python, index.py, --clean-data, /tmp/outputs/Clean_Data/data]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /secret/gcp-credentials/service-creds.json}
      - {name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE, value: /secret/gcp-credentials/service-creds.json}
      image: stevedev7/black-friday:clean-data-04
      volumeMounts:
      - {mountPath: /secret/gcp-credentials, name: gcp-credentials-service-creds}
    outputs:
      artifacts:
      - {name: clean-data-Clean-Data, path: /tmp/outputs/Clean_Data/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.9
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Fill
          Nan values and generate dummy variables", "implementation": {"container":
          {"command": ["python", "index.py", "--clean-data", {"outputPath": "Clean
          Data"}], "image": "stevedev7/black-friday:clean-data-04"}}, "name": "Clean
          Data", "outputs": [{"description": "Path to processed dataset", "name":
          "Clean Data", "type": "LocalPath"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "cd5f5e86a2c057c4482753fa3acee40c35679028b1ee4e065983f98886f9e27b", "url":
          "components/clean-data/clean-data.yml"}'}
    volumes:
    - name: gcp-credentials-service-creds
      secret: {secretName: service-creds}
  - name: v-black-friday-v2
    dag:
      tasks:
      - {name: clean-data, template: clean-data}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
